# Generated by Django 5.0.14 on 2026-08-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventoryalert'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailysalesrecord',
            new_name='forecasting_product_68def1_idx',
            old_name='forecasting_product_saledate_idx',
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='current_stock',
            field=models.IntegerField(help_text='Historical stock snapshot on this date, kept for reference/backtesting.'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='safety_stock_level',
            field=models.IntegerField(help_text='Buffer stock target for this product at the time of this record.'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Null when the record is a chain-wide aggregate rather than one branch.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='supplier_lead_time_days',
            field=models.IntegerField(help_text='Days between placing a PO and delivery, at the time of this record.'),
        ),
    ]
