# Generated by Django 5.0.14 on 2026-08-14 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed')], default='Preparing', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.purchaseorder'),
        ),
    ]
