# Generated by Django 5.0.14 on 2026-08-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
