# Generated by Django 5.0.14 on 2026-09-01 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shift_order_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=150)),
                ('business_sector', models.CharField(choices=[('Grocery Store', 'Grocery Store'), ('Convenience Store', 'Convenience Store'), ('Supermarket', 'Supermarket'), ('Minimart', 'Minimart'), ('Pharmacy', 'Pharmacy'), ('Restaurant / F&B', 'Restaurant / F&B'), ('Bakery', 'Bakery'), ('Electronics', 'Electronics'), ('Fashion & Apparel', 'Fashion & Apparel'), ('Other', 'Other')], default='Other', max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh (GMT+7)', max_length=50)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('VIP', 'VIP')], default='Bronze', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('last_contacted_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceChannelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50, unique=True)),
                ('connected', models.BooleanField(default=False)),
                ('store_partner_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('account_detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['method'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('price', 'Price')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.product')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
