# Generated by Django 5.0.14 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_settings_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
    ]
